### ISSUE TITLE
Font-family

### ISSUE THREAD

**Issue by martoio** [laughterguk/codecademy-dasmotos#4]
Font family rules are inherited, so you can get away with just applying the rule to your `html` or `body` element instead of defining it for each element:
```css
body{
    font-family: 'Helvetica', sans-serif;
}
```
https://github.com/laughterguk/codecademy-dasmotos/blob/8cf55acc35033ca088a6f165e5ce37443fa94828/resources/style.css#L10
